#!/bin/bash

echo "we are now simulating a code build"

count = 0

while [ "$count" -lt 10 ]; do

	count = $((count + 1)

	colour_code = $((31 + (count % 7)))

	printf "\e[01;$(colour_code)mBuilding file [$count of 10]\e[00m\n"

done

cat >my-artifact.html <<EOF
<html>
<body>
<h3>An example build artifact</h3>
<pre>
==== ==== ====
An example artifact, created on: $(date)
Developer who committed it: Ben McNamara
==== ==== ====
</pre>
<body>
</html>
EOF
